# put your configuration values here

[runtime]
log_level="WARNING"  # the system log level of dlt
# use the dlthub_telemetry setting to enable/disable anonymous usage data reporting, see https://dlthub.com/docs/reference/telemetry
dlthub_telemetry = true

[sources.google_sheets]
spreadsheet_url_or_id = "1peX3hTtpfWMJ4Xu3QNG37aRnJ6DCtjtZDMELsjCws9U" # please set me up!
range_names = ["Sheet1!A1:F21","Sheet2!A22:F51"] # please set me up!
